---
- hosts: all
  vars_files:
  - ./defaults/main.yaml
  - ./vars/main.yaml
  roles:
  - { role: hashicorp, become: yes, tags: hashicorp }
  tasks:
  - name: Test role as a playbook
    import_tasks: tasks/main.yaml
    become: true
  handlers:
  - include: handlers/main.yaml
