# Build packer vm template
- name: Build packer vm template
  ansible.builtin.command:
  args:
    cmd: "packer build -force -var-file vcenter.pkr.hcl -var-file variables.pkr.hcl build.pkr.hcl"
    chdir: "./{{ ansible_user }}/{{ item.name }}"
  loop: "{{ packer_builds }}"
  tags:
    - packer_build
    - packer_build_template

- name: Copy artifacts to local
  ansible.posix.synchronize:
    src: "./{{ ansible_user }}/{{ item.name }}"
    dest: "../artifacts/"
    mode: pull
    rsync_opts:
      - "--no-motd"
      - "--exclude=packer_cache"
      - "--exclude=vcenter.pkr.hcl"
  loop: "{{ packer_builds }}"
  tags:
    - fetch
